theme = "Catppuccin-mocha"
client_id = "a42365a56b104c84878c9b46b29b41a9" # spotify connect device
# client_id = "65b708073fc0480ea92a077233ca87bd" # web app device
# client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "||"
liked_icon = " "
border_type = "Rounded"
progress_bar_type = "Rectangle"
playback_window_position = "Bottom"
playback_window_width = 4
enable_media_control = true
enable_streaming = "Always"
enable_cover_image_cache = true
default_device = "spire"

[copy_command]
command = "xclip"
args = ["-sel", "c"]

[device]
name = "spire"
device_type = "speaker"
autoplay = true
volume = 70
bitrate = 320
audio_cache = false
normalization = false
